services:
  - type: web
    name: todoapp
    runtime: docker
    plan: free
    region: oregon
    healthCheckPath: /
    envVars:
      - key: ASPNETCORE_ENVIRONMENT
        value: Production
      - key: PORT
        value: "8080"
    buildCommand: docker build -t todoapp .
    startCommand: docker run -p 8080:8080 todoapp
