services:
  - type: web
    name: todoapp
    env: docker
    plan: free
    region: oregon
    healthCheckPath: /
    envVars:
      - key: ASPNETCORE_ENVIRONMENT
        value: Production
      - key: ASPNETCORE_URLS
        value: http://0.0.0.0:8080
    buildCommand: docker build -t todoapp .
    startCommand: docker run -p 8080:8080 todoapp
